global:
  scrape_interval: 15s

scrape_configs:
  - job_name: tournabot
    static_configs:
      - targets: ["bot:9108"]

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
